sprint 11 Add database
AlkhasK/java-filmorate pull request #5
Opened 2022-12-06 10:01 UTC by AlkhasK

2022-12-07 12:38 UTC, alexache requested changes

2022-12-07 12:38 UTC, alexache commented on pom.xml
> +        <dependency>
Автоформатирование может помочь выправить отступы

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Это можно сделать и одной ломбок аннотацией - @RequiredArgsConstructor

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +    Integer userId;
Не хватает модификаторов доступа

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    Integer id;
Модификаторы доступа

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +    Integer filmId;
Модификаторы доступа

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/MPA.java
> +public class MPA {
Более правильно именовать Mpa

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +public class Friend {
Для чего нам нужна эта сущность в Java?

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +public class Like {
И эта сущность для чего?

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Optional<Film> film = filmStorage.findById(filmId);
(опционально) С Optional проще будет return film.orElseThrow(() -> new EntityNotFoundException(...));

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (!validateFilmService.isEntityExists(filmId)) {
(опционально) Не уверен, что дополнительный сервис действительно нужен, можно ведь напрямую в стораджа получать как в методе выше?

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Like like = new Like(filmId, userId);
Вот здесь можно было просто передавать айди фильма и юзера в сторадж лайков без дополнительного предстваления этой связи

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/mpa/MPAService.java
> +public class MPAService {
Тоже более правильно MpaService

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    .forEach(genreId -> filmGenreStorage.create(filmId, genreId));
(опционально) Лучше бы это сделать как батч апдейт по всему списку жанров одним батч запросом (jdbcTemplate.batchUpdate(). Иначе запросы к ьазе в цикле не очень хороши

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Optional<MPA> filmMpa = mpaStorage.findById(filmMpaId);
Это не лучший вариант, нужно делать JOIN при селекте на таблицу MPA

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                "where u.USER_ID in ((select FRIEND_ID from FRIENDS where USER_ID = ? union select USER_ID " +
Вложенные запросы - это плохо, особенно когда их столько. Лучше постараться переписать через джоины

2022-12-07 12:38 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Genre> filmGenres = genreStorage.findByFilmId(filmId);
Это работает для запросов по 1 фильму, а если список фильмов, то нужно получать жанры для тех фильмов одним запросом к базе, а не в цикле

2022-12-11 01:21 UTC, AlkhasK commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +public class Friend {
Не могу понять, что исправить

2022-12-11 01:21 UTC, AlkhasK commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +public class Like {
Не могу понять, что исправить

2022-12-12 09:21 UTC, alexache requested changes

2022-12-12 09:21 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +public class Friend {
Это скорее опциональный комментарий, но мне кажется можно обойтись без этого класса. мы можем оперировать этой таблицей просто парой user_id, other_user_id,

2022-12-12 09:21 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Genre> filmGenres = genreStorage.findByFilmId(filmId);
Этот комментарий еще очень актуален - не должно быть запросов к базе в цикле, а при вызове из findAll это именно что в цикле

2022-12-14 06:30 UTC, alexache approved these changes

2022-12-19 11:05 UTC, merged